[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler.git"
    commit = "c5b7d62e02211dbe5528eed1d76392676004d829"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler/releases/download/v0.1.2/colink-protocol-coflows-scheduler-linux-x86_64.tar.gz"
    sha256 = "1a1db11762726c9de512337e0b3be311b5a22d42a9f09bb9c3012044a1c71990"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler/releases/download/v0.1.2/colink-protocol-coflows-scheduler-macos-x86_64.tar.gz"
    sha256 = "dc8e925b4cc0dbe4f6f81cb16dd263080bb89f9a5c580595d7bda363686d64bf"
