[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler.git"
    commit = "7d79b06c718c3c2b99ef428480264df25dabf074"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler/releases/download/v0.1.1/colink-protocol-coflows-scheduler-linux-x86_64.tar.gz"
    sha256 = "669aefb77e595f2704a1f4064e403da0fe4ee7207f25a83a87fe886dc8985671"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-coflows-scheduler/releases/download/v0.1.1/colink-protocol-coflows-scheduler-macos-x86_64.tar.gz"
    sha256 = "f9d86c4ad199fb9383e4926ab15587efa2806d950b941c7c74ee15d8862f8d80"
