[package]
name = "greetings"
keywords = ["greetings"]
description = "greetings"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-greetings-dev.git"
    commit = "d3d57940a7235bc3597914a1d44762fc5f14b738"
