[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev.git"
    commit = "f63e9f7c4e2128d6419f9e522ee6f23aba0e4d57"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev/releases/download/v0.1.3/colink-protocol-greetings-linux-x86_64.tar.gz"
    sha256 = "18956669d9c4357288fd4635115175e320db1e10d5fd937d7220b1519779be90"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev/releases/download/v0.1.3/colink-protocol-greetings-macos-x86_64.tar.gz"
    sha256 = "772323c98ed302b8b8e479739634a01de82d975847cc2b6c489e6ae9ea0e0398"
