[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev.git"
    commit = "ce698b2943a74308cb2b7c42fa6a156cd7086c93"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev/releases/download/test2/colink-protocol-greetings-linux-x86_64.tar.gz"
    sha256 = "550aa2541e6283a38694837c04b4188be4947049fde86a8706435fece327755b"
