[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev.git"
    commit = "5b2e963815fe33709e44b7f33f16acf508ba2343"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev/releases/download/v0.1.2/colink-protocol-greetings-linux-x86_64.tar.gz"
    sha256 = "9ab170c51dced909194266aef8926ad01adab8652624c334db310cd61d94e144"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-greetings-dev/releases/download/v0.1.2/colink-protocol-greetings-macos-x86_64.tar.gz"
    sha256 = "fda5af05ab2fa3639d9628505b3dbec58317cda88d446d286e032afb8c7bbbcd"
