[package]
name = "policy_module"
keywords = ["policy module"]
description = "policy module"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-policy-module-dev.git"
    commit = "6a53c1e389a4ca1639c420973f2acc9be9a7876d"
