[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev.git"
    commit = "309e5bcb375e9797421beef66f36938efbf8b519"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev/releases/download/v0.1.3/colink-protocol-policy-module-linux-x86_64.tar.gz"
    sha256 = "57e1ce8183d8ef152f045f0c0ae3aa8158c826ac85061f554489953f54ee80e1"
