[package]
name = "policy_module"
keywords = ["policy module"]
description = "policy module"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-policy-module-dev.git"
    commit = "c5dafc90e6477ac75810eb2e264a0cc79fac422f"
