[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev.git"
    commit = "da760285a1824b5b16e97d90846541c7d008cd34"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev/releases/download/v0.1.4/colink-protocol-policy-module-linux-x86_64.tar.gz"
    sha256 = "679f523740253505c332a9d3939b92ee01573ba8a355227ad4993aef16c6840b"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev/releases/download/v0.1.4/colink-protocol-policy-module-macos-x86_64.tar.gz"
    sha256 = "f2dd030d8ff22d7d57d7c7778db463bc3aafd842a021c7673e9adf801fa5f900"
