[package]
name = "policy_module"
keywords = ["policy module"]
description = "policy module"

[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev.git"
    commit = "7afe83bd32185ff0501f8d51a249f3aeacb38256"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-policy-module-dev/releases/download/v0.1.1/colink-protocol-policy-module-linux-x86_64.tar.gz"
    sha256 = "276979fb75b5db360519a381d1b94fa8b29c887b0ed8c2602ba46ad708f49a09"
