[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-registry-dev.git"
    commit = "15ea019e40465a532a1601a8cc3f4b0e6fe3fd45"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-registry-dev/releases/download/v0.1.5/colink-protocol-registry-linux-x86_64.tar.gz"
    sha256 = "410b1d46d45102ffc5e94f558b183d6b2f62fbed7a9feab873b883b20bb0fbb5"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-registry-dev/releases/download/v0.1.5/colink-protocol-registry-macos-x86_64.tar.gz"
    sha256 = "3bd6b4de6deee37dbe560135e42f9094cf7f068c2810096ca4a87cfd2ab357f8"
