[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-registry-dev.git"
    commit = "01e0ef53020b0cac2bdd312c740ef366c39e927f"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-registry-dev/releases/download/v0.1.1/colink-protocol-registry-linux-x86_64.tar.gz"
    sha256 = "c2fe5bd6b4c97363bba367f21ce9a02e5a6dec1318381c1506a85aec2cf0b8aa"
