[package]
name = "registry"
keywords = ["registry"]
description = "registry"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-registry-dev.git"
    commit = "70334f94461113d9588be96595014d2cd3f3f722"
