[package]
name = "remote_storage"
keywords = ["remote storage"]
description = "remote storage"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-remote-storage-dev.git"
    commit = "8d291f8543922e6dc50c27c3e17285304fed17f7"
