[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-remote-command-dev.git"
    commit = "aac5c75bcddce8fea3bf2330b3c95c6a0de61946"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-remote-command-dev/releases/download/v0.1.1/colink-protocol-remote-command-linux-x86_64.tar.gz"
    sha256 = "e31859cf36d5767cd288e776913fb7eeea09f50c12197600e9df7affb70b8eb2"
