[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev.git"
    commit = "b8d8aeffa920279ab9b3cfc29e528ce6b33ca4a8"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.2/colink-protocol-s3h-linux-x86_64.tar.gz"
    sha256 = "9dd52a50a2cd2d4c716811b0216889da7295239fc10862cd788def8c72c9f3b4"
