[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev.git"
    commit = "707aed0ee94635bd9f70fa6e182535f79630c8a2"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.5/colink-protocol-s3h-linux-x86_64.tar.gz"
    sha256 = "0c8116a8bd36a08f4d39f22adb7eb6f91945721260db8b1b5ecb59f025d667c9"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.5/colink-protocol-s3h-macos-x86_64.tar.gz"
    sha256 = "d9e8b2ec178bc7c8e28cc33dcc96c9ac84da0b3bd0202a9f24b7810e9759eada"
