[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev.git"
    commit = "9f448e2e92534c177b15c7582de977a081e67ea4"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.3/colink-protocol-s3h-linux-x86_64.tar.gz"
    sha256 = "374fedb71f8386cce4787aef1cc550740c658825b4d5bca1f5266c4f8157ba8e"
