[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev.git"
    commit = "a2673687a530d9cd844b3f612e4556699948f922"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.4/colink-protocol-s3h-linux-x86_64.tar.gz"
    sha256 = "57165c872983160c396ba0d2b28bdf0283544e85176a7dba8483f00d978c2d9c"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.4/colink-protocol-s3h-macos-x86_64.tar.gz"
    sha256 = "e62204585fb79a291fbb45767e4a2b7569023ad9ff328b7ae30f12b2f2a89bf3"
