[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev.git"
    commit = "89a3791948a539cd601165b70953332b1fe4479e"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.6/colink-protocol-s3h-linux-x86_64.tar.gz"
    sha256 = "318e08876362fcea23d11f9d6ac3a2c495235d75b7fe81316a6eee551dfa418e"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-s3h-dev/releases/download/v0.1.6/colink-protocol-s3h-macos-x86_64.tar.gz"
    sha256 = "49e6fc3d4c9f1858c3ed91ad30b724b91ff41f5089ca1278bb8680cbda751c89"
