[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-telegram-bot-dev.git"
    commit = "eb390a0d520b793003f1586deb7ec81239ef29e8"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-telegram-bot-dev/releases/download/v0.1.4/colink-protocol-telegram-bot-linux-x86_64.tar.gz"
    sha256 = "ee0057bcf467e8ae7f7f7a0dd35f3c5d2a8fd6272a50617cdfa5d9d5a2f13d8b"
    [binary.macos-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-telegram-bot-dev/releases/download/v0.1.4/colink-protocol-telegram-bot-macos-x86_64.tar.gz"
    sha256 = "8e26ff21dd15cb2a43e8511dd703d4e046bceedf2d9de3cf539b858b3d91dabf"
