[package]
name = "telegram_bot"
keywords = ["telegram bot"]
description = "telegram bot"

[source]
    [source.git]
    url = "git@github.com:CoLearn-Dev/colink-protocol-telegram-bot-dev.git"
    commit = "a16956fa187786404cd1582870512c07e1513004"
