[source]
    [source.git]
    url = "https://github.com/CoLearn-Dev/colink-protocol-telegram-bot-dev.git"
    commit = "7c564ae8c7a60e008a32741758561b22bf80da76"

[binary]
    [binary.linux-x86_64]
    url = "https://github.com/CoLearn-Dev/colink-protocol-telegram-bot-dev/releases/download/v0.1.2/colink-protocol-telegram-bot-linux-x86_64.tar.gz"
    sha256 = "1aef2ade9d1b3616a339de876ca19f0d8349da6f7243cba06b3d534091a7c0d2"
